import nodemailer from "nodemailer";

export default async function handler(req, res) {
	if (req.method !== "POST") {
		return res.status(405).json({ success: false, error: "Method not allowed" });
	}

	const { name, email, message } = req.body;

	if (!name || !email || !message) {
		return res.status(400).json({ success: false, error: "All fields are required." });
	}
	if (email.length > 150 || !email.includes("@")) {
		return res.status(400).json({ success: false, error: "Invalid email address." });
	}
	if (message.length > 2000) {
		return res.status(400).json({ success: false, error: "Message exceeds character limit." });
	}

	const transporter = nodemailer.createTransport({
		host: process.env.SMTP_HOST || "smtp.gmail.com",
		port: 465,
		secure: true,
		auth: {
			user: process.env.SMTP_USER,
			pass: process.env.SMTP_PASS
		}
	});
	const safeMessage = message.replace(/</g, "&lt;").replace(/>/g, "&gt;");
	try {
		await transporter.sendMail({
			from: `"${name}" <${process.env.SMTP_USER}>`,
			to: process.env.RECEIVER_EMAIL,
			replyTo: email,
			subject: `📩 Website Message from ${name}`,
			text: `Name: ${name}\nEmail: ${email}\n\nMessage:\n${message}`,
			html: `
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body { font-family: Arial, sans-serif; color: #333333; line-height: 1.6; background-color: #FAFAFA; margin: 0; padding: 20px; }
                        .container { max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e0e0e0; border-radius: 8px; background-color: #ffffff; box-shadow: 0 2px 4px rgba(0,0,0,0.02); }
                        .header { font-size: 20px; font-weight: bold; margin-bottom: 24px; color: #2C3E50; border-bottom: 2px solid #ECF0F1; padding-bottom: 12px; }
                        .info-table { width: 100%; margin-bottom: 24px; border-collapse: collapse; }
                        .info-table td { padding: 8px 0; font-size: 14px; }
                        .info-table td.label { font-weight: bold; width: 90px; color: #7F8C8D; }
                        .message-title { font-size: 14px; font-weight: bold; color: #2C3E50; margin-bottom: 8px; }
                        .message-box { background-color: #F8F9FA; padding: 16px; border-left: 4px solid #3498DB; border-radius: 4px; font-size: 14px; white-space: pre-wrap; color: #4A4A4A; }
                        .footer { margin-top: 24px; font-size: 12px; color: #95A5A6; text-align: center; border-top: 1px solid #ECF0F1; padding-top: 12px; }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <div class="header">📩 New Contact Form Inquiry</div>
                        
                        <table class="info-table">
                            <tr>
                                <td class="label">Name:</td>
                                <td style="color: #2C3E50; font-weight: 500;">${name}</td>
                            </tr>
                            <tr>
                                <td class="label">Email:</td>
                                <td><a href="mailto:${email}" style="color: #3498DB; text-decoration: none;">${email}</a></td>
                            </tr>
                        </table>
                        
                        <div class="message-title">Message:</div>
                        <div class="message-box">${safeMessage}</div>
                        
                        <div class="footer">
                            This email was automatically generated by your website's contact form.
                        </div>
                    </div>
                </body>
                </html>
            `
		});

		return res.status(200).json({ success: true, message: "Email sent successfully!" });
	} catch (error) {
		console.error("SMTP Error:", error);

		return res.status(500).json({ success: false, error: "Failed to process email delivery." });
	}
}
